name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install JSHint
        run: npm install -g jshint
      - name: Run Linter
        run: |
          jshint --esversion 8 ./giftlink-backend/**/*.js

  client_build:
    runs-on: ubuntu-latest
    needs: lint_js
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies and build frontend
        run: |
          cd giftlink-frontend
          npm install
          npm run build
